name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/main.yml
  # Manual dispatch
  workflow_dispatch:
env:
  FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
jobs:
  Build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          mkdir --parents /etc/docker/certs.d/hub.stidard.dev/
          openssl s_client -showcerts -connect hub.stidard.dev < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/docker/certs.d/hub.stidard.dev/ca.crt
          docker build --build-arg="VUE_APP_GRAPHQL_HTTP=http://server:8000/graphql" --build-arg="VUE_APP_GRAPHQL_WS=ws://server:8000/subscriptions" --build-arg="FONT_AWESOME_TOKEN=${FONT_AWESOME_TOKEN}" -t hub.stidard.dev/dixtionary-web:latest .
          docker push hub.stidard.dev/dixtionary-web:latest
